stages:
  create-intermediate-data:
    cmd: python src/stages/create-intermediate-data.py --config params.yaml
    deps:
    - src/stages/create-intermediate-data.py
    params:
    - base
    - create-intermediate-data
    outs:
    - data/interim/md.csv
    - data/interim/md_test.csv
    - data/interim/data.pkl
    - data/interim/data_test.pkl
  data-split:
    cmd: python src/stages/data-split.py --config params.yaml
    deps:
    - src/stages/data-split.py
    - data/interim/md.csv
    - data/interim/md_test.csv
    params:
    - base
    - create-intermediate-data
    - data-split
    outs:
    - data/splits/train.csv
    - data/splits/val.csv
    - data/splits/test.csv
