stages:
  data-split:
    cmd: python src/stages/data-split.py --config params.yaml
    deps:
      - src/stages/data-split.py
      - ${base.raw-data-zip}
    params:
      - base
      - data-split
    outs:
      - ${data-split.train-split}
      - ${data-split.val-split}
      - ${data-split.test-split}

  # Error detection
  create-error-detection-dataset:
    cmd: python src/stages/create-error-detection-dataset.py --config params.yaml
    deps:
      - src/stages/create-error-detection-dataset.py
      - ${data-split.train-split}
      - ${data-split.val-split}
      - ${data-split.test-split}
      - ${base.raw-data-zip}
    params:
      - base
      - create-error-detection-dataset
    outs:
      - ${create-error-detection-dataset.dataset}
  train-error-detection:
    cmd: python src/stages/train-error-detection.py --config params.yaml
    deps:
      - src/stages/train-error-detection.py
      - ${create-error-detection-dataset.dataset}
    params:
      - base
      - create-error-detection-dataset
      - train-error-detection
    outs:
      - ${train-error-detection.train-log}:
          cache: false
      - ${train-error-detection.output-dir}
  predict-test-set-error-detection:
    cmd: python src/stages/predict-test-set-error-detection.py --config params.yaml
    deps:
      - src/stages/predict-test-set-error-detection.py
      - ${create-error-detection-dataset.dataset}
      - ${train-error-detection.output-dir}
    params:
      - base
      - create-error-detection-dataset
      - train-error-detection
      - predict-test-set-error-detection
    outs:
      - ${predict-test-set-error-detection.test-log}:
          cache: false
      - ${predict-test-set-error-detection.predictions}
  convert-predictions-to-icdar-output:
    cmd: python src/stages/convert-predictions-to-icdar-output.py --config params.yaml
    deps:
      - src/stages/convert-predictions-to-icdar-output.py
      - ${base.raw-data-zip}
      - ${create-error-detection-dataset.dataset}
      - ${predict-test-set-error-detection.predictions}
    params:
      - base
      - train-error-detection
      - predict-test-set-error-detection
      - convert-predictions-to-icdar-output
    outs:
      - ${convert-predictions-to-icdar-output.icdar-output-json}
  evaluate-error-detection:
    cmd: python src/stages/run-icdar-evaluation.py ${base.raw-data-zip} ${convert-predictions-to-icdar-output.icdar-output-json} ${evaluate-error-detection.icdar-output-csv} ${base.loglevel}
    deps:
      - src/stages/run-icdar-evaluation.py
      - ${base.raw-data-zip}
      - ${convert-predictions-to-icdar-output.icdar-output-json}
    params:
      - base
      - predict-test-set-error-detection
      - convert-predictions-to-icdar-output
      - evaluate-error-detection
    outs:
      - ${evaluate-error-detection.icdar-output-csv}
  generate-error-detection-report:
    cmd: python src/stages/generate-error-detection-report.py --config params.yaml
    deps:
      - src/stages/generate-error-detection-report.py
      - templates/report-error-detection.md
      - ${train-error-detection.train-log}
      - ${predict-test-set-error-detection.test-log}
      - ${evaluate-error-detection.icdar-output-csv}
    params:
      - base
      - data-split
      - create-error-detection-dataset
      - train-error-detection
      - predict-test-set-error-detection
      - evaluate-error-detection
    outs:
      - ${generate-error-detection-report.report-file}:
          cache: false
    metrics:
      - ${generate-error-detection-report.metrics}:
          cache: false

  # Error correction
  create-error-correction-dataset:
    cmd: python src/stages/create-error-correction-dataset.py --config params.yaml
    deps:
      - src/stages/create-error-correction-dataset.py
      - ${data-split.val-split}
      - ${base.raw-data-zip}
    params:
      - base
      - create-error-correction-dataset
    outs:
      - ${create-error-correction-dataset.dataset}
  train-error-correction:
    cmd: python src/stages/train-error-correction.py --config params.yaml
    deps:
      - src/stages/train-error-correction.py
      - ${create-error-correction-dataset.dataset}
    params:
      - base
      - create-error-correction-dataset
      - train-error-correction
    outs:
      - ${train-error-correction.train-log}:
          cache: false
      - ${train-error-correction.model-save-path}
  predict-error-correction:
    cmd: >
      python src/stages/predict-error-correction.py
      --error-correction-dataset ${create-error-correction-dataset.dataset}
      --hidden-size ${train-error-correction.hidden-size}
      --dropout ${train-error-correction.dropout}
      --max-len ${train-error-correction.max-len}
      --teacher-forcing-ratio ${train-error-correction.teacher-forcing-ratio}
      --model-path ${train-error-correction.model-save-path}
      --batch-size ${train-error-correction.batch-size}
      --calculate-loss
      --test-log-file ${predict-error-correction.test-log}
      --raw-dataset ${base.raw-data-zip}
      --predictions-out-perfect-error-detection ${predict-error-correction.predictions-out-perfect-error-detection}
      --results-error-detection-model ${convert-predictions-to-icdar-output.icdar-output-json}
      --predictions-out-error-detection-model ${predict-error-correction.predictions-out-error-detection-model}
      --loglevel ${base.loglevel}
    deps:
      - src/stages/predict-error-correction.py
      - ${create-error-correction-dataset.dataset}
      - ${base.raw-data-zip}
      - ${convert-predictions-to-icdar-output.icdar-output-json}
    params:
      - base
      - create-error-correction-dataset
      - train-error-correction
      - convert-predictions-to-icdar-output
      - predict-error-correction
    outs:
      - ${predict-error-correction.test-log}
      - ${predict-error-correction.predictions-out-perfect-error-detection}
      - ${predict-error-correction.predictions-out-error-detection-model}
  generate-perfect-icdar-json:
    cmd: >
      python src/stages/generate-perfect-icdar-json.py
      --raw-dataset ${base.raw-data-zip}
      --out-file-detection ${generate-perfect-icdar-json.out-file-detection}
      --out-file-correction ${generate-perfect-icdar-json.out-file-correction}
    deps:
      - src/stages/generate-perfect-icdar-json.py
      - ${base.raw-data-zip}
    params:
      - base
      - generate-perfect-icdar-json
    outs:
      - ${generate-perfect-icdar-json.out-file-detection}
      - ${generate-perfect-icdar-json.out-file-correction}
