stages:
  data-split:
    cmd: python src/stages/data-split.py --config params.yaml
    deps:
    - src/stages/data-split.py
    params:
    - base
    - data-split
    outs:
    - data/splits/train.csv
    - data/splits/val.csv
    - data/splits/test.csv
  create-error-detection-dataset:
    cmd: python src/stages/create-error-detection-dataset.py --config params.yaml
    deps:
    - src/stages/create-error-detection-dataset.py
    - data/splits/train.csv
    - data/splits/val.csv
    - data/splits/test.csv
    params:
    - base
    - create-error-detection-dataset
    outs:
    - data/processed/correction-dataset
  train-error-detection:
    cmd: python src/stages/train-error-detection.py --config params.yaml
    deps:
    - src/stages/train-error-detection.py
    - data/processed/correction-dataset
    params:
    - base
    - create-error-detection-dataset
    - train-error-detection
    outs:
    - error-detection-train-log.csv:
        cache: false
    - models/error-detection/
