stages:
  data-split:
    cmd: python src/stages/data-split.py --config params.yaml
    deps:
    - src/stages/data-split.py
    - ${base.raw-data-zip}
    params:
    - base
    - data-split
    outs:
    - ${data-split.train-split}
    - ${data-split.val-split}
    - ${data-split.test-split}
  create-error-detection-dataset:
    cmd: python src/stages/create-error-detection-dataset.py --config params.yaml
    deps:
    - src/stages/create-error-detection-dataset.py
    - ${data-split.train-split}
    - ${data-split.val-split}
    - ${data-split.test-split}
    - ${base.raw-data-zip}
    params:
    - base
    - create-error-detection-dataset
    outs:
    - ${create-error-detection-dataset.dataset}
  train-error-detection:
    cmd: python src/stages/train-error-detection.py --config params.yaml
    deps:
    - src/stages/train-error-detection.py
    - ${create-error-detection-dataset.dataset}
    params:
    - base
    - create-error-detection-dataset
    - train-error-detection
    outs:
    - ${train-error-detection.train_log}:
        cache: false
    - ${train-error-detection.output_dir}
