base:
  loglevel: INFO
  seed: 8232
  raw-data-zip: data/raw/ICDAR2019_POCR_competition_dataset.zip
data-split:
  val-size: 0.1
  train-split: data/splits/train.csv
  val-split: data/splits/val.csv
  test-split: data/splits/test.csv
create-error-detection-dataset:
  size: 35
  step: 30
  max-edit-distance: 0.3
  dataset: data/processed/detection-dataset
train-error-detection:
  pretrained-model-name: bert-base-multilingual-cased
  output_dir: models/error-detection/
  evaluation_strategy: epoch
  num_train_epochs: 3
  load_best_model_at_end: True
  save_strategy: epoch
  per_device_train_batch_size: 16
  train_log: error-detection-train-log.csv
  delete-checkpoints: True
