base:
  loglevel: INFO
  seed: 8232
  raw-data-zip: data/raw/ICDAR2019_POCR_competition_dataset.zip
data-split:
  val-size: 0.1
  train-split: data/splits/train.csv
  val-split: data/splits/val.csv
  test-split: data/splits/test.csv

# Error detection
create-error-detection-dataset:
  size: 35
  step: 30
  max-edit-distance: 0.3
  dataset: data/processed/detection-dataset
train-error-detection:
  pretrained-model-name: bert-base-multilingual-cased
  output-dir: models/error-detection/
  evaluation-strategy: epoch
  num-train-epochs: 3
  load-best-model-at-end: True
  save-strategy: epoch
  per-device-train-batch-size: 16
  train-log: results/detection/logs/train-log.csv
  delete-checkpoints: True
predict-test-set-error-detection:
  per-device-eval-batch-size: 16
  test-log: results/detection/logs/test-log.csv
  predictions: results/detection/predictions.npy
convert-predictions-to-icdar-output:
  icdar-output-json: results/detection/icdar_predictions.json
evaluate-error-detection:
  icdar-output-csv: results/detection/icdar_evaluation_results.csv
generate-error-detection-report:
  metrics: reports/detection/metrics.json
  report-file: reports/detection/experiment_results.md

# Error correction
create-error-correction-dataset:
  dataset: data/processed/correction-dataset/dataset.csv
train-error-correction:
  max-len: 22
  batch-size: 256
  model-save-path: models/error-correction/model.rar
  hidden-size: 256
  dropout: 0.1
  teacher-forcing-ratio: 0.5
  num-epochs: 25
  valid-niter: 5
  max-num-patience: 5
  max-num-trial: 5
  lr-decay: 0.5
  train-log: results/correction/logs/train-log.csv
predict-error-correction:
  test-log: results/correction/logs/test-log.csv
  perfect-detection-out: results/correction/perfect-detection+predicted-correction.csv
  predicted-detection-out: results/correction/predicted-detection+predicted-correction.csv
generate-perfect-icdar-json:
  out-file-detection: results/perfect/perfect-detection.json
  out-file-correction: results/perfect/perfect-detection+correction.json
