base:
  loglevel: INFO
  seed: 8232
  raw-data-zip: data/raw/ICDAR2019_POCR_competition_dataset.zip
data-split:
  val-size: 0.1
  train-split: data/splits/train.csv
  val-split: data/splits/val.csv
  test-split: data/splits/test.csv
create-error-detection-dataset:
  size: 35
  step: 30
  max-edit-distance: 0.3
  dataset: data/processed/detection-dataset
train-error-detection:
  pretrained-model-name: bert-base-multilingual-cased
  output-dir: models/error-detection/
  evaluation-strategy: epoch
  num-train-epochs: 3
  load-best-model-at-end: True
  save-strategy: epoch
  per-device-train-batch-size: 16
  train-log: results/detection/logs/train-log.csv
  delete-checkpoints: True
evaluate-error-detection:
  test-log: results/detection/logs/test-log.csv
  icdar-output-json: results/detection/icdar_predictions.json
  icdar-output-csv: results/detection/icdar_evaluation_results.csv
  report-file: reports/detection/experiment_results.md
