base:
  loglevel: INFO
  seed: 8232
get-raw-data:
create-intermediate-data:
  raw-data-zip: data/raw/ICDAR2019_POCR_competition_dataset.zip
  intermediate-train-md-csv: data/interim/md.csv
  intermediate-test-md-csv: data/interim/md_test.csv
  intermediate-train-texts: data/interim/data.pkl
  intermediate-test-texts: data/interim/data_test.pkl
data-split:
  val-size: 0.1
  train-split: data/splits/train.csv
  val-split: data/splits/val.csv
  test-split: data/splits/test.csv
create-error-detection-dataset:
  size: 35
  step: 30
  max-edit-distance: 0.3
  dataset: data/processed/correction-dataset
train-error-detection:
  pretrained-model-name: bert-base-multilingual-cased
  output_dir: models/error-detection/
  evaluation_strategy: epoch
  num_train_epochs: 3
  load_best_model_at_end: True
  save_strategy: epoch
  per_device_train_batch_size: 16
  train_log: error-detection-train-log.csv
