base:
  seed: 8232
  raw-data-zip: data/raw/ICDAR2019_POCR_competition_dataset.zip
  dev-mode: no-dev # One of dev, no-dev
data-split:
  val-size: 0.1
  train-split: data/splits/train.csv
  val-split: data/splits/val.csv
  test-split: data/splits/test.csv

# Error detection
create-error-detection-dataset:
  size: 35
  step: 30
  max-edit-distance: 0.3
  dataset: data/processed/detection-dataset
train-error-detection:
  pretrained-model-name: bert-base-multilingual-cased
  output-dir: models/error-detection/
  evaluation-strategy: epoch
  num-train-epochs: 3
  save-strategy: epoch
  per-device-train-batch-size: 16
  train-log: results/detection/logs/train-log.csv
predict-test-set-error-detection:
  per-device-eval-batch-size: 16
  test-log: results/detection/logs/test-log.csv
  predictions: results/detection/predictions.npy
convert-error-detection-predictions-to-icdar-output:
  icdar-output-json: results/detection/icdar_predictions.json
evaluate-error-detection:
  icdar-output-csv: results/detection/icdar_evaluation_results.csv
generate-error-detection-report:
  metrics: reports/detection/metrics.json
  report-file: reports/detection/experiment_results.md

# Error correction
error-correction-base:
  dev-mode: no-dev # One of dev, no-dev
create-error-correction-dataset:
  dataset: data/processed/correction-dataset/dataset.csv
train-error-correction:
  max-len: 22
  batch-size: 16
  model-dir: models/error-correction-model
  num-epochs: 1
  valid-niter: 5000
  model-name: google/byt5-small
  train-log: results/correction/logs/train-log.csv
calculate-loss-error-correction:
  batch-size: 64
  test-log: results/correction/logs/test-log.csv
predict-error-correction:
  batch-size: 32
  perfect-detection-out: results/correction/perfect-detection+predicted-correction.csv
  predicted-detection-out: results/correction/predicted-detection+predicted-correction.csv
generate-perfect-icdar-json:
  out-file-detection: results/perfect/perfect-detection.json
  out-file-correction: results/perfect/perfect-detection+correction.json
convert-perfect-correction-predicted-detection-results-to-icdar-format:
  out-file: results/correction/perfect-detection+predicted-correction.json
evaluate-error-correction-perfect-detection:
  icdar-output-csv: results/correction/icdar-evaluation-perfect-detection+predicted-correction.csv
convert-predicted-correction-predicted-detection-results-to-icdar-format:
  out-file: results/correction/predicted-detection+predicted-correction.json
evaluate-error-correction-predicted-detection:
  icdar-output-csv: results/correction/icdar-evaluation-predicted-detection+predicted-correction.csv
generate-error-correction-report:
  metrics: reports/correction/metrics.json
  report-file: reports/correction/experiment_results.md
